DROP TABLE menu_platos;
DROP TABLE plato_ingredientes;
DROP TABLE menus;
DROP TABLE platos;
DROP TABLE ingredientes;

CREATE TABLE menus(

    id BIGINT GENERATED ALWAYS AS IDENTITY,
    nombre VARCHAR(100),
    precio NUMERIC(5,2),
    desde DATE,
    hasta DATE,

    CONSTRAINT "PK_MENUS" PRIMARY KEY (id),
    CONSTRAINT "NN_MENUS.NOMBRE" CHECK ( nombre IS NOT NULL ),
    CONSTRAINT "NN_MENUS.PRECIO" CHECK ( precio IS NOT NULL),
    CONSTRAINT "NN_MENUS.DESDE" CHECK ( desde IS NOT NULL),
    CONSTRAINT "NN_MENUS.HASTA" CHECK ( hasta IS NOT NULL)
);


CREATE TABLE platos(

    id BIGINT GENERATED ALWAYS AS IDENTITY,
    nombre VARCHAR(150),
    descripcion VARCHAR(450),
    precio NUMERIC(5,2),
    tipo VARCHAR(9),

    CONSTRAINT "PK_PLATOS" PRIMARY KEY (id),
    CONSTRAINT "NN_PLATOS.NOMBRE" CHECK (nombre IS NOT NULL),
    CONSTRAINT "UK_PLATOS.NOMBRE" UNIQUE (nombre),
    CONSTRAINT "NN_PLATOS.PRECIO" CHECK (precio IS NOT NULL),
    CONSTRAINT "NN_PLATOS.DESCRIPCION" CHECK (descripcion IS NOT NULL),
    CONSTRAINT "NN_PLATOS.TIPO" CHECK (tipo IS NOT NULL),
    CONSTRAINT "CH_PLATOS.TIPO" CHECK (tipo IN ('ENTRANTE', 'PRINCIPAL', 'POSTRE', 'INFANTIL'))
);

CREATE TABLE menu_platos(

    id_menu BIGINT,
    id_platos BIGINT,

    CONSTRAINT "PK_MENUS_PLATOS.ID_MENU" PRIMARY KEY (id_menu, id_platos),
    CONSTRAINT "FK_MENUS_PLATOS.ID_MENUS" FOREIGN KEY (id_menu)
        REFERENCES menus(id),
    CONSTRAINT "FK_MENUS_PLATOS.ID_PLATOS" FOREIGN KEY (id_platos)
        REFERENCES platos(id)
);

CREATE TABLE ingredientes(

    id BIGINT GENERATED ALWAYS AS IDENTITY,
    nombre VARCHAR(150),
    unidad VARCHAR(10),

    CONSTRAINT "PK_INGREDIENTES" PRIMARY KEY (id),
    CONSTRAINT "NN_INGREDIENTES.NOMBRE" CHECK ( nombre IS NOT NULL ),
    CONSTRAINT "UK_INGREDIENTES.NOMBRE" UNIQUE (nombre),
    CONSTRAINT "NN_INGREDIENTES.UNIDAD" CHECK ( unidad IS NOT NULL),
    CONSTRAINT "CH_INGREDIENTES.UNIDAD" CHECK ( unidad IN ('GRAMO', 'UNIDAD', 'CENTILITRO'))
);

CREATE TABLE plato_ingredientes(

     id_platos BIGINT,
     id_ingrediente BIGINT,
     cantidad SMALLINT,

     CONSTRAINT "PK_PLATO_INGREDIENTES.ID_INGREDIENTES" PRIMARY KEY (id_ingrediente, id_platos),
     CONSTRAINT "FK_PLATO_INGREDIENTES.ID_INGREDIENTES" FOREIGN KEY (id_ingrediente)
        REFERENCES ingredientes(id),
     CONSTRAINT "FK_PLATO_INGREDIENTES.ID_PLATOS" FOREIGN KEY (id_platos)
        REFERENCES platos(id),
     CONSTRAINT "NN_PLATO_INGREDIENTES.CANTIDAD" CHECK ( cantidad IS NOT NULL),
     CONSTRAINT "CH_PLATO_INGRADIENTES.CANTIDAD" CHECK (cantidad > 0 AND cantidad <= 9999)

);

